# Generated by Django 4.0 on 2024-03-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
